export const allQuotes: { [key: string]: string[] } = {
  Motivation: [
    " Push yourself, because no one else is going to do it for you. ",
    " Don’t watch the clock; do what it does. Keep going. ",
    " Great things never come from comfort zones. ",
    " Wake up with determination. Go to bed with satisfaction. ",
    " Do something today that your future self will thank you for. ",
    " Dream it. Wish it. Do it. ",
    " The harder you work for something, the greater you’ll feel when you achieve it. ",
    " Don’t stop when you’re tired. Stop when you’re done. ",
    " Little things make big days. ",
    " The best way to predict the future is to create it. ",
    " Believe you can and you're halfway there. ",
    " The only way to do great work is to love what you do. ",
    " Success is not final, failure is not fatal: it is the courage to continue that counts. ",
    " If you are determined to learn, no one can stop you. ",
    " Strive for progress, not perfection. ",
  ],
  Hope: [
    " Hope is the thing with feathers that perches in the soul. ",
    " Where there is no hope, it is necessary to invent it. ",
    " Optimism is the faith that leads to achievement. ",
    " Hope is being able to see that there is light despite all of the darkness. ",
    " To hope means to be ready at every moment for that which is not yet born. ",
    " Never lose hope. Storms make people stronger. ",
    " Hope is a good thing, maybe the best of things, and no good thing ever dies. ",
    " Yesterday is not ours to recover, but tomorrow is ours to win or lose. ",
    " In every adversity, there is a seed of an equivalent or greater benefit. ",
    " We must accept finite disappointment, but never lose infinite hope. ",
    " When you have exhausted all possibilities, remember this: you haven't. ",
    " Keep your eyes on the stars, and your feet on the ground. ",
    " The darkest night is often the bridge to the brightest tomorrow. ",
    " Hope is a waking dream. ",
    " Don't give up. The beginning is always the hardest. ",
  ],
  Creativity: [
    " Creativity is intelligence having fun. ",
    " The chief enemy of creativity is 'good' sense. ",
    " Every artist was first an amateur. ",
    " Don't think. Just do. ",
    " Creativity takes courage. ",
    " The best way to predict the future is to create it. ",
    " You can't use up creativity. The more you use, the more you have. ",
    " Imagination is the beginning of creation. ",
    " The desire to create is one of the deepest yearnings. ",
    " Be regular and orderly in your life, so you may be violent and original in your work. ",
    " Creativity is seeing what everyone else has seen, and thinking what no one else has thought. ",
    " Logic will get you from A to B. Imagination will take you everywhere. ",
    " The creative adult is the child who survived. ",
    " An idea is a point of departure and no more. ",
    " Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. ",
  ],
  Gratitude: [
    " Gratitude turns what we have into enough. ",
    " The roots of all goodness lie in the soil of appreciation for goodness. ",
    " Be thankful for what you have; you'll end up having more. ",
    " Gratitude is not only the greatest of virtues but the parent of all others. ",
    " Appreciation is a wonderful thing: It makes what is excellent in others belong to us as well. ",
    " Feeling gratitude and not expressing it is like wrapping a present and not giving it. ",
    " Let us be grateful to the people who make us happy. ",
    " When you are grateful, fear disappears and abundance appears. ",
    " The more you praise and celebrate your life, the more there is in life to celebrate. ",
    " Gratitude is the fairest blossom which springs from the soul. ",
    " Silent gratitude isn't much use to anyone. ",
    " It is not happiness that brings us gratitude. It is gratitude that brings us happiness. ",
    " The unthankful heart discovers no mercies; but the thankful heart discovers mercies in everything. ",
    " In ordinary life, we hardly realize that we receive a great deal more than we give, and that it is only with gratitude that this balance can be restored. ",
    " Cultivate the habit of being grateful for every good thing that comes to you. ",
  ],
  Wisdom: [
    " The only true wisdom is in knowing you know nothing. ",
    " Knowledge speaks, but wisdom listens. ",
    " The greater the island of knowledge, the longer the coastline of wonder. ",
    " It is better to remain silent and be thought a fool than to open one's mouth and remove all doubt. ",
    " Never mistake motion for action. ",
    " The only good is knowledge and the only evil is ignorance. ",
    " Wisdom begins in wonder. ",
    " The fool doth think he is wise, but the wise man knows himself to be a fool. ",
    " To acquire knowledge, one must study; but to acquire wisdom, one must observe. ",
    " Doubt is the beginning, not the end, of wisdom. ",
    " The price of anything is the amount of life you exchange for it. ",
    " What you think, you become. What you feel, you attract. What you imagine, you create. ",
    " A wise man gets more use from his enemies than a fool from his friends. ",
    " It is easier to build strong children than to repair broken men. ",
    " The quieter you become, the more you can hear. ",
  ],
  Life: [
    " The unexamined life is not worth living. ",
    " Life is 10% what happens to us and 90% how we react to it. ",
    " The purpose of our lives is to be happy. ",
    " Life is what happens when you're busy making other plans. ",
    " Live as if you were to die tomorrow. Learn as if you were to live forever. ",
    " In three words I can sum up everything I've learned about life: it goes on. ",
    " Don't cry because it's over, smile because it happened. ",
    " The grand essentials to happiness in this life are something to do, something to love, and something to hope for. ",
    " Life is a journey that must be traveled no matter how bad the roads and accommodations. ",
    " Do not take life too seriously. You will never get out of it alive. ",
    " The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate. ",
    " Life is a succession of lessons which must be lived to be understood. ",
    " To live is the rarest thing in the world. Most people just exist. ",
    " Keep your face always toward the sunshine—and shadows will fall behind you. ",
    " Life's challenges are not supposed to paralyze you, they're supposed to help you discover who you are. ",
  ],
  Empathy: [
    " Empathy is seeing with the eyes of another, listening with the ears of another, and feeling with the heart of another. ",
    " The highest form of knowledge is empathy. ",
    " Could a greater miracle take place than for us to look through each other's eyes for an instant?",
    " Empathy is about finding echoes of another person in yourself. ",
    " When you start to develop your powers of empathy and imagination, it's as if you live a thousand lives. ",
    " The only way to change someone's mind is to connect with them from the heart. ",
    " No matter how much you know, if you don't have empathy, you are poor. ",
    " Empathy is a quality of character that can change the world. ",
    " We rise by lifting others. ",
    " The little things? The little moments? They aren't little. ",
    " One of the most important things you can do is let people know they are not alone. ",
    " Walk a mile in their shoes before you judge them. ",
    " Empathy is a choice, and it's a vulnerable choice. ",
    " The great gift of human beings is the power of empathy. ",
    " Be kind, for everyone you meet is fighting a harder battle. ",
  ],
  Courage: [
    " Courage is not the absence of fear, but the triumph over it. ",
    " It takes courage to grow up and become who you really are. ",
    " A ship in harbor is safe, but that is not what ships are built for. ",
    " Courage is resistance to fear, mastery of fear – not absence of fear. ",
    " The real man smiles in trouble, gathers strength from distress, and grows brave by reflection. ",
    " Do not follow where the path may lead. Go instead where there is no path and leave a trail. ",
    " Only those who dare to fail greatly can ever achieve greatly. ",
    " Fortune favors the bold. ",
    " It takes courage to be happy. ",
    " The greatest test of courage on earth is to bear defeat without losing heart. ",
    " Without courage, we cannot practice any other virtue with consistency. ",
    " Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen. ",
    " You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face. ",
    " Courage is being scared to death, but saddling up anyway. ",
    " The difference between a successful person and others is not a lack of strength, but a lack of will. ",
  ],
  Friendship: [
    " Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'",
    " A true friend is someone who is always there for you, even when they don't have to be. ",
    " Friends are the family we choose for ourselves. ",
    " A single rose can be my garden... a single friend, my world. ",
    " Friendship is not about who you've known the longest. It's about who walked into your life and stayed. ",
    " Good friends are like stars. You don't always see them, but you know they're always there. ",
    " A real friend is one who walks in when the rest of the world walks out. ",
    " There is nothing on this earth more to be prized than true friendship. ",
    " The greatest gift of life is friendship. ",
    " True friends are never apart, maybe in distance but never in heart. ",
    " Friendship multiplies the good in life and divides its evils. ",
    " The only way to have a friend is to be one. ",
    " Many people will walk in and out of your life, but only true friends will leave footprints in your heart. ",
    " A sweet friendship refreshes the soul. ",
    " Friends show their love in times of trouble, not just in happiness. ",
  ],
  Confidence: [
    " Believe you can and you're halfway there. ",
    " Confidence comes from discipline and training. ",
    " The most beautiful thing you can wear is confidence. ",
    " With self-discipline, anything is possible. ",
    " Confidence is silent. Insecurities are loud. ",
    " Optimism is the faith that leads to achievement. ",
    " The future belongs to those who believe in their dreams. ",
    " If you have no confidence, you are twice defeated. ",
    " Being yourself is the greatest accomplishment. ",
    " The best way to gain self-confidence is to face your fears. ",
    " Self-confidence is a superpower; magic happens when you believe. ",
    " Lack of confidence is not a lack of ability. ",
    " Confidence isn't 'they will like me'; it's 'I'll be fine if they don't'. ",
    " Don't wait for perfect conditions. Start now. ",
    " Confidence in our bodies, minds, and spirits allows new adventures. ",
  ],
  Success: [
    " Success is not final, failure is not fatal: it is the courage to continue that counts. ",
    " The only place where success comes before work is in the dictionary. ",
    " Success is walking from failure to failure with no loss of enthusiasm. ",
    " The best revenge is massive success. ",
    " Action is the foundational key to all success. ",
    " Success usually comes to those who are too busy to be looking for it. ",
    " Strive not to be a success, but rather to be of value. ",
    " Success is not the key to happiness. Happiness is the key to success. ",
    " The road to success and the road to failure are almost exactly the same. ",
    " I attribute my success to this: I never gave or took any excuse. ",
    " Your level of success is determined by your level of discipline and perseverance. ",
    " The secret of success is to do the common thing uncommonly well. ",
    " Success is the sum of small efforts, repeated day in and day out. ",
    " If you want to achieve greatness, stop asking for permission. ",
    " Success is liking yourself, liking what you do, and liking how you do it. ",
  ],
  Relationship: [
    " A true relationship is two imperfect people refusing to give up on each other. ",
    " Relationships are like plants. They need nurturing and attention to grow. ",
    " The strongest relationships are built on trust and respect. ",
    " Love is not about possession. It is about appreciation. ",
    " Communication is the key to any successful relationship. ",
    " A great relationship is about two things: Appreciating the similarities and respecting the differences. ",
    " Shared joy is a double joy; shared sorrow is half sorrow. ",
    " The best way to mend a broken heart is time and girlfriends. ",
    " No relationship is ever a waste of time. Every experience is a lesson. ",
    " The quality of your life is the quality of your relationships. ",
    " It takes two to tango, but only one to break the connection. ",
    " Compromise is not a weakness; it's a strength in relationships. ",
    " Every relationship has its ups and downs, but it's how you handle them that counts. ",
    " Love isn't finding a perfect person. It's seeing an imperfect person perfectly. ",
    " The best connections are the ones that help you grow, not shrink. ",
  ],
  Happiness: [
    " Happiness is not something ready-made. It comes from your own actions. ",
    " The only joy in the world is to begin. ",
    " The best way to cheer yourself is to cheer somebody else up. ",
    " Happiness is a choice. You can choose to be happy. ",
    " For every minute you are angry you lose sixty seconds of happiness. ",
    " The more you praise and celebrate your life, the more there is in life to celebrate. ",
    " Happiness resides not in possessions, and not in gold, happiness dwells in the soul. ",
    " The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less. ",
    " Be happy for this moment. This moment is your life. ",
    " Happiness is when what you think, what you say, and what you do are in harmony. ",
    " It is not how much we have, but how much we enjoy, that makes happiness. ",
    " The greatest happiness you can have is knowing that you do not necessarily require happiness. ",
    " Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared. ",
    " Joy does not simply happen to us. We have to choose joy and keep choosing it every day. ",
    " Simplicity, contentment, and spontaneity are the keys to happiness. ",
  ],
};
