export const allQuotes: { [key: string]: string[] } = {
  Resilience: [
    "Push yourself, because no one else is going to do it for you.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Great things never come from comfort zones.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Dream it. Wish it. Do it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Little things make big days.",
    "The strongest steel is forged in the hottest fire.",
    "What doesn't kill you makes you stronger.",
    "Fall seven times, stand up eight.",
    "Storms make trees take deeper roots.",
    "The only way out is through.",
    "Tough times never last, but tough people do.",
  ],
  Growth: [
    "The only way to do great work is to love what you do.",
    "Your comfort zone is a beautiful place, but nothing ever grows there.",
    "Strive for progress, not perfection.",
    "The expert in anything was once a beginner.",
    "Don't be afraid to give up the good to go for the great.",
    "Every moment is a fresh beginning.",
    "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.",
    "The mind is everything. What you think you become.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "The journey of a thousand miles begins with a single step.",
    "Change the way you look at things and the things you look at change.",
    "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
    "It's not about perfect. It's about effort. And when you bring that effort every single day, that's where transformation happens.",
    "Growth is never by mere chance; it is the result of forces working together.",
  ],
  Creativity: [
    "Creativity is intelligence having fun.",
    "The chief enemy of creativity is 'good' sense.",
    "Every artist was first an amateur.",
    "Don't think. Just do.",
    "Creativity takes courage.",
    "The best way to predict the future is to create it.",
    "You can't use up creativity. The more you use, the more you have.",
    "Imagination is the beginning of creation. You imagine what you desire, you will what you imagine, and at last, you create what you will.",
    "The desire to create is one of the deepest yearnings of the human soul.",
    "Be regular and orderly in your life, so that you may be violent and original in your work.",
    "Creativity is seeing what everyone else has seen, and thinking what no one else has thought.",
    "Logic will get you from A to B. Imagination will take you everywhere.",
    "The creative adult is the child who survived.",
    "An idea is a point of departure and no more. As soon as you elaborate it, it becomes transformed by the materials, by the ideas of others, and by the social context in which it is made.",
    "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something.",
  ],
  Gratitude: [
    "Gratitude turns what we have into enough.",
    "The roots of all goodness lie in the soil of appreciation for goodness.",
    "Be thankful for what you have; you'll end up having more.",
    "Gratitude is not only the greatest of virtues but the parent of all others.",
    "Appreciation is a wonderful thing: It makes what is excellent in others belong to us as well.",
    "Feeling gratitude and not expressing it is like wrapping a present and not giving it.",
    "Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.",
    "When you are grateful, fear disappears and abundance appears.",
    "The more you praise and celebrate your life, the more there is in life to celebrate.",
    "Gratitude is the fairest blossom which springs from the soul.",
    "Silent gratitude isn't much use to anyone.",
    "It is not happiness that brings us gratitude. It is gratitude that brings us happiness.",
    "The unthankful heart discovers no mercies; but the thankful heart discovers mercies in everything.",
    "In ordinary life, we hardly realize that we receive a great deal more than we give, and that it is only with gratitude that this balance can be restored.",
    "Cultivate the habit of being grateful for every good thing that comes to you, and to give thanks continuously. And because all things have contributed to your advancement, you should include all things in your gratitude.",
  ],
  Wisdom: [
    "The only true wisdom is in knowing you know nothing.",
    "Knowledge speaks, but wisdom listens.",
    "The greater the island of knowledge, the longer the coastline of wonder.",
    "It is better to remain silent and be thought a fool than to open one's mouth and remove all doubt.",
    "Never mistake motion for action.",
    "The only good is knowledge and the only evil is ignorance.",
    "Wisdom begins in wonder.",
    "The fool doth think he is wise, but the wise man knows himself to be a fool.",
    "To acquire knowledge, one must study; but to acquire wisdom, one must observe.",
    "Doubt is the beginning, not the end, of wisdom.",
    "The price of anything is the amount of life you exchange for it.",
    "What you think, you become. What you feel, you attract. What you imagine, you create.",
    "A wise man gets more use from his enemies than a fool from his friends.",
    "It is easier to build strong children than to repair broken men.",
    "The quieter you become, the more you can hear.",
  ],
  Purpose: [
    "The two most important days in your life are the day you are born and the day you find out why.",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
    "He who has a *why* to live can bear almost any *how*.",
    "Definiteness of purpose is the starting point of all achievement.",
    "Your work is to discover your world and then with all your heart give yourself to it.",
    "The meaning of life is to find your gift. The purpose of life is to give it away.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Purpose is an essential element for a good life.",
    "The purpose of our lives is to be happy.",
    "Life has no meaning unless one lives it with a purpose.",
    "Knowing your purpose is the first step toward living a life of significance.",
    "Don't just exist, live. Don't just live, live with purpose.",
    "The soul which has no fixed purpose in life is lost; to be everywhere, is to be nowhere.",
    "Your true purpose is to be yourself.",
    "The strongest man in the world is he who stands most alone.",
  ],
  Empathy: [
    "Empathy is seeing with the eyes of another, listening with the ears of another, and feeling with the heart of another.",
    "The highest form of knowledge is empathy.",
    "Could a greater miracle take place than for us to look through each other's eyes for an instant?",
    "Empathy is about finding echoes of another person in yourself.",
    "When you start to develop your powers of empathy and imagination in this way, it's as if you start to live a thousand lives.",
    "The only way to change someone's mind is to connect with them from the heart.",
    "No matter how much you know, no matter how clever you are, if you don't have empathy, you are poor.",
    "Empathy is a quality of character that can change the world.",
    "We rise by lifting others.",
    "The little things? The little moments? They aren't little.",
    "One of the most important things you can do on this earth is to let people know they are not alone.",
    "Walk a mile in their shoes before you judge them.",
    "Empathy is a choice, and it's a vulnerable choice. In order to connect with you, I have to connect with something in myself that knows that feeling.",
    "The great gift of human beings is that we have the power of empathy, we can all sense a mysterious connection to each other.",
    "Be kind, for everyone you meet is fighting a harder battle.",
  ],
  Courage: [
    "Courage is not the absence of fear, but the triumph over it.",
    "It takes courage to grow up and become who you really are.",
    "A ship in harbor is safe, but that is not what ships are built for.",
    "Courage is resistance to fear, mastery of fear – not absence of fear.",
    "The real man smiles in trouble, gathers strength from distress, and grows brave by reflection.",
    "Do not follow where the path may lead. Go instead where there is no path and leave a trail.",
    "Only those who dare to fail greatly can ever achieve greatly.",
    "Fortune favors the bold.",
    "It takes courage to be happy.",
    "The greatest test of courage on earth is to bear defeat without losing heart.",
    "Without courage, we cannot practice any other virtue with consistency. We can't be kind, true, merciful, generous, or honest.",
    "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.",
    "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.",
    "Courage is being scared to death, but saddling up anyway.",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.",
  ],
  Simplicity: [
    "Simplicity is the ultimate sophistication.",
    "The greatest wealth is to live content with little.",
    "Less is more.",
    "Life is really simple, but we insist on making it complicated.",
    "Purity and simplicity are the two wings with which man soars into the heavens.",
    "One day, I will find the right words, and they will be simple.",
    "Truth is ever to be found in the simplicity, and not in the multiplicity and confusion of things.",
    "Simplicity is the keynote of all true elegance.",
    "The art of being wise is the art of knowing what to overlook.",
    "Nature does not hurry, yet everything is accomplished.",
    "It takes a certain kind of genius to make things simple.",
    "Make everything as simple as possible, but no simpler.",
    "Simplicity, clarity, singleness: These are the attributes that give our lives power and make them revolutionary. ",
    "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.",
    "Live simply so that others may simply live.",
  ],
  Connection: [
    "We are all connected; to each other, biologically. To the Earth, chemically. To the rest of the universe, atomically.",
    "The greatest gift of life is friendship, and I have received it.",
    "The more you connect with others, the more you connect with yourself.",
    "Individual commitment to a group effort—that is what makes a team work, a company work, a society work, a civilization work.",
    "No man is an island, entire of itself; every man is a piece of the continent, a part of the main.",
    "To connect with others, we must first connect with ourselves.",
    "Shared joy is a double joy; shared sorrow is half sorrow.",
    "The quality of your life is the quality of your relationships.",
    "We are wired for connection.",
    "Alone we can do so little; together we can do so much.",
    "Love is a force more formidable than any other. It is invisible—it cannot be seen or measured, yet it is powerful enough to transform you in a moment, and offer you more joy than any material possession could.",
    "Connection is why we're here; it is what gives purpose and meaning to our lives.",
    "The beauty of connection is that it's a two-way street. You receive as much as you give.",
    "The greatest thing you'll ever learn is just to love and be loved in return.",
    "Kindness is a bridge between all people.",
  ],
  Perseverance: [
    "It's not whether you get knocked down, it's whether you get up.",
    "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
    "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
    "Perseverance is not a long race; it is many short races one after the other.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The harder the struggle, the more glorious the triumph.",
    "Press on. Nothing in the world can take the place of persistence.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "Believe you can and you're halfway there.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "The moment you're about to give up is usually the moment right before a miracle happens. Don't give up.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Through perseverance, many people win success out of what seemed destined to be certain failure.",
    "The only way to fail is to quit.",
    "Patience, persistence and perspiration make an unbeatable combination for success.",
  ],
  Joy: [
    "Joy is not in things; it is in us.",
    "Find joy in the ordinary.",
    "The most joyful people are those who give the most.",
    "Joy does not simply happen to us. We have to choose joy and keep choosing it every day.",
    "Happiness is a choice. Joy is a connection.",
    "Let your joy be unconfined.",
    "Joy is prayer; joy is strength: joy is love; joy is a net of love by which you can catch souls.",
    "The essence of all beautiful art, all great art, is gratitude.",
    "Wherever you go, no matter what the weather, always bring your own sunshine.",
    "A joyful heart is the normal result of a heart burning with love.",
    "Give thanks for a little and you will find a lot.",
    "Joy is not a season, it's a state of mind.",
    "Simplicity, contentment, and spontaneity are the keys to joy.",
    "Joy resides in the moments of conscious appreciation.",
    "The purest form of joy is found in giving without expectation.",
  ],
};
